language: node_js
sudo: false
node_js:
- lts/*
deploy:
  provider: npm
  email: henri.bergius@iki.fi
  api_key:
    secure: BRsTBHeyBbbDcALK1oMkeBk2bfaiJ8KRu8ABChBNOOVC0DQPsv2H2qRIxHlc2wTfSTJb0J9YG/AZAZ3cXy58r88vNDJyRBotZlvI+Jjq4TEm7m2vv45FZVWaf1Llbi2bOhe+BzEgk+sCP0mAZYh1jM+p3lkCPL9T2XQ4nzzXpTE=
  on:
    tags: true
    repo: noflo/noflo-nodejs
